# Generated by Django 4.2.7 on 2025-09-21 19:03

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Category name (e.g., 'Food', 'Salary', 'Transport')", max_length=100)),
                ('type', models.CharField(choices=[('income', 'Income'), ('expense', 'Expense')], help_text='Whether this category is for income or expenses', max_length=10)),
                ('description', models.TextField(blank=True, help_text='Optional description of what this category covers')),
                ('color', models.CharField(default='#007bff', help_text='Hex color code for UI display (e.g., #FF5733)', max_length=7)),
                ('icon', models.CharField(blank=True, help_text="Icon name for UI display (e.g., 'food', 'transport')", max_length=50)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this category is currently in use')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(help_text='User who owns this category', on_delete=django.db.models.deletion.CASCADE, related_name='categories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['type', 'name'],
                'unique_together': {('name', 'user', 'type')},
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Transaction amount in Ghana Cedis (GHS)', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('type', models.CharField(choices=[('income', 'Income'), ('expense', 'Expense'), ('transfer', 'Transfer')], help_text='Type of transaction', max_length=10)),
                ('description', models.CharField(help_text='Brief description of the transaction', max_length=255)),
                ('notes', models.TextField(blank=True, help_text='Additional notes or details about the transaction')),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('mobile_money', 'Mobile Money'), ('bank_transfer', 'Bank Transfer'), ('card', 'Debit/Credit Card'), ('cheque', 'Cheque'), ('online', 'Online Payment')], default='cash', help_text='How the payment was made', max_length=20)),
                ('reference_number', models.CharField(blank=True, help_text='Transaction reference (mobile money ref, bank ref, etc.)', max_length=100)),
                ('date', models.DateField(help_text='Date when the transaction occurred')),
                ('location', models.CharField(blank=True, help_text='Where the transaction took place', max_length=200)),
                ('receipt_image', models.ImageField(blank=True, help_text='Photo of receipt or proof of transaction', null=True, upload_to='receipts/%Y/%m/')),
                ('is_recurring', models.BooleanField(default=False, help_text='Whether this is a recurring transaction')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, help_text='Category this transaction belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='transactions.category')),
                ('user', models.ForeignKey(help_text='User who made this transaction', on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['user', 'date'], name='transaction_user_id_8af7f1_idx'), models.Index(fields=['user', 'type'], name='transaction_user_id_4685bf_idx'), models.Index(fields=['category'], name='transaction_categor_e3f163_idx')],
            },
        ),
    ]
