# Generated by Django 4.2.7 on 2025-09-21 19:53

import apps.transactions.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='color',
            field=models.CharField(default='#007bff', help_text='Hex color code for UI display (e.g., #FF5733)', max_length=7, validators=[apps.transactions.models.validate_hex_color]),
        ),
    ]
