# Generated by Django 4.2.7 on 2025-09-21 20:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_add_hex_color_validator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='color',
            field=models.CharField(default='#007bff', help_text='Hex color code for UI display (e.g., #FF5733)', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a valid hex color code', regex='^#[0-9A-Fa-f]{6}$')]),
        ),
    ]
