# Generated by Django 4.2.7 on 2025-09-21 19:03

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('transactions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Budget name (e.g., 'Monthly Food Budget')", max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Budget limit amount in Ghana Cedis (GHS)', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('period', models.CharField(choices=[('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly'), ('custom', 'Custom Period')], default='monthly', help_text='Budget period type', max_length=20)),
                ('start_date', models.DateField(help_text='When this budget period starts')),
                ('end_date', models.DateField(help_text='When this budget period ends')),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed'), ('exceeded', 'Exceeded')], default='active', help_text='Current status of this budget', max_length=20)),
                ('alert_percentage', models.IntegerField(default=80, help_text='Send alert when spending reaches this percentage of budget', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('description', models.TextField(blank=True, help_text='Optional description of budget goals or notes')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this budget is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(help_text='Category this budget applies to', on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to='transactions.category')),
                ('user', models.ForeignKey(help_text='User who owns this budget', on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-start_date', 'category__name'],
            },
        ),
        migrations.CreateModel(
            name='BudgetAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('threshold', 'Threshold Reached'), ('exceeded', 'Budget Exceeded'), ('daily_reminder', 'Daily Reminder'), ('weekly_summary', 'Weekly Summary')], help_text='Type of alert', max_length=20)),
                ('message', models.TextField(help_text='Alert message content')),
                ('percentage_at_alert', models.DecimalField(decimal_places=2, help_text='Budget percentage when alert was triggered', max_digits=5)),
                ('is_read', models.BooleanField(default=False, help_text='Whether user has read this alert')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('budget', models.ForeignKey(help_text='Budget this alert relates to', on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='budgets.budget')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='budget',
            index=models.Index(fields=['user', 'status'], name='budgets_bud_user_id_60f731_idx'),
        ),
        migrations.AddIndex(
            model_name='budget',
            index=models.Index(fields=['start_date', 'end_date'], name='budgets_bud_start_d_b133e8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='budget',
            unique_together={('user', 'category', 'start_date', 'end_date')},
        ),
    ]
