# Generated by Django 4.2.7 on 2025-09-21 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='budget',
            constraint=models.CheckConstraint(check=models.Q(('start_date__lt', models.F('end_date'))), name='budget_valid_date_range'),
        ),
    ]
